import { createElement } from 'lwc';
import Create_Account_Record_WIth_LWC from 'c/create_Account_Record_WIth_LWC';

describe('c-create-account-record-w-ith-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-create-account-record-w-ith-lwc', {
            is: Create_Account_Record_WIth_LWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});