public class Test1 {
    
    
    public static void method1(){
        system.debug('static Void Method');
    }
    
    public static integer method2(){
      integer  abc = 2 ;
        return abc ;
    }
    
     public static string city = 'Nagpur';
  public static string country = 'India';
    
    public static void indexcal(integer age , string Name , Integer Phone){
        system.debug('Full Name :'+ Name);
         system.debug('Phone Number :'+ Phone);
         system.debug('age :'+ age);
         system.debug('country :'+ country);
         system.debug('city :'+ city);
    }
}